# Generated by Django 3.0.2 on 2020-04-16 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20200414_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='auction_expiration_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
