# Generated by Django 3.0.2 on 2020-04-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_items_auction_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='item_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_status',
            field=models.CharField(choices=[('OFFERS', 'Offers'), ('COMPLETED', 'Completed')], max_length=20),
        ),
    ]
