# Generated by Django 3.0.2 on 2020-04-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_bidding_auction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='item_owner',
            field=models.CharField(default='', max_length=60),
        ),
    ]
