# Generated by Django 3.0.2 on 2020-04-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_bidding_item_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='user_bidding',
        ),
    ]
